### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by KMEHSilhouette**

### CODE REVIEW

**Comment by Elephant1214** [comment]
I should be able to finish 0.2.0, which will add wool stairs and slabs, tomorrow. Might as well add all of the translations and then merge with 0.2.0 to save time.

**Comment by KMEHSilhouette** [comment]
you can give me new addons with txt and I send it to you directly asap

**Comment by Elephant1214** [comment]
Here's the updated lang file, it was also changed to match the correct name for the mod.
```
tile.nev.white_concrete_stairs.name=White Concrete Stairs
tile.nev.orange_concrete_stairs.name=Orange Concrete Stairs
tile.nev.magenta_concrete_stairs.name=Magenta Concrete Stairs
tile.nev.light_blue_concrete_stairs.name=Light Blue Concrete Stairs
tile.nev.yellow_concrete_stairs.name=Yellow Concrete Stairs
tile.nev.lime_concrete_stairs.name=Lime Concrete Stairs
tile.nev.pink_concrete_stairs.name=Pink Concrete Stairs
tile.nev.gray_concrete_stairs.name=Gray Concrete Stairs
tile.nev.light_gray_concrete_stairs.name=Light Gray Concrete Stairs
tile.nev.cyan_concrete_stairs.name=Cyan Concrete Stairs
tile.nev.purple_concrete_stairs.name=Purple Concrete Stairs
tile.nev.blue_concrete_stairs.name=Blue Concrete Stairs
tile.nev.brown_concrete_stairs.name=Brown Concrete Stairs
tile.nev.green_concrete_stairs.name=Green Concrete Stairs
tile.nev.red_concrete_stairs.name=Red Concrete Stairs
tile.nev.black_concrete_stairs.name=Black Concrete Stairs

tile.nev.white_concrete_slab.name=White Concrete Slab
tile.nev.orange_concrete_slab.name=Orange Concrete Slab
tile.nev.magenta_concrete_slab.name=Magenta Concrete Slab
tile.nev.light_blue_concrete_slab.name=Light Blue Concrete Slab
tile.nev.yellow_concrete_slab.name=Yellow Concrete Slab
tile.nev.lime_concrete_slab.name=Lime Concrete Slab
tile.nev.pink_concrete_slab.name=Pink Concrete Slab
tile.nev.gray_concrete_slab.name=Gray Concrete Slab
tile.nev.light_gray_concrete_slab.name=Light Gray Concrete Slab
tile.nev.cyan_concrete_slab.name=Cyan Concrete Slab
tile.nev.purple_concrete_slab.name=Purple Concrete Slab
tile.nev.blue_concrete_slab.name=Blue Concrete Slab
tile.nev.brown_concrete_slab.name=Brown Concrete Slab
tile.nev.green_concrete_slab.name=Green Concrete Slab
tile.nev.red_concrete_slab.name=Red Concrete Slab
tile.nev.black_concrete_slab.name=Black Concrete Slab

tile.nev.white_wool_stairs.name=White Wool Stairs
tile.nev.orange_wool_stairs.name=Orange Wool Stairs
tile.nev.magenta_wool_stairs.name=Magenta Wool Stairs
tile.nev.light_blue_wool_stairs.name=Light Blue Wool Stairs
tile.nev.yellow_wool_stairs.name=Yellow Wool Stairs
tile.nev.lime_wool_stairs.name=Lime Wool Stairs
tile.nev.pink_wool_stairs.name=Pink Wool Stairs
tile.nev.gray_wool_stairs.name=Gray Wool Stairs
tile.nev.light_gray_wool_stairs.name=Light Gray Wool Stairs
tile.nev.cyan_wool_stairs.name=Cyan Wool Stairs
tile.nev.purple_wool_stairs.name=Purple Wool Stairs
tile.nev.blue_wool_stairs.name=Blue Wool Stairs
tile.nev.brown_wool_stairs.name=Brown Wool Stairs
tile.nev.green_wool_stairs.name=Green Wool Stairs
tile.nev.red_wool_stairs.name=Red Wool Stairs
tile.nev.black_wool_stairs.name=Black Wool Stairs

tile.nev.white_wool_slab.name=White Wool Slab
tile.nev.orange_wool_slab.name=Orange Wool Slab
tile.nev.magenta_wool_slab.name=Magenta Wool Slab
tile.nev.light_blue_wool_slab.name=Light Blue Wool Slab
tile.nev.yellow_wool_slab.name=Yellow Wool Slab
tile.nev.lime_wool_slab.name=Lime Wool Slab
tile.nev.pink_wool_slab.name=Pink Wool Slab
tile.nev.gray_wool_slab.name=Gray Wool Slab
tile.nev.light_gray_wool_slab.name=Light Gray Wool Slab
tile.nev.cyan_wool_slab.name=Cyan Wool Slab
tile.nev.purple_wool_slab.name=Purple Wool Slab
tile.nev.blue_wool_slab.name=Blue Wool Slab
tile.nev.brown_wool_slab.name=Brown Wool Slab
tile.nev.green_wool_slab.name=Green Wool Slab
tile.nev.red_wool_slab.name=Red Wool Slab
tile.nev.black_wool_slab.name=Black Wool Slab

itemGroup.nev.not_enough_variations=Not Enough Variations
```

**Comment by KMEHSilhouette** [comment]
upadte addon
[update.txt](https://github.com/Elephant1214/NotEnoughVariations/files/8305814/update.txt)
s

**Pull request closed without merging**
